// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StundenPlanApp.Data;

#nullable disable

namespace StundenPlanApp.Migrations
{
    [DbContext(typeof(StundenplanDbContext))]
    partial class StundenplanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StundenPlanApp.Models.Klasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Klassen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "INF22"
                        },
                        new
                        {
                            Id = 2,
                            Name = "INF23"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ELT22"
                        });
                });

            modelBuilder.Entity("StundenPlanApp.Models.Lehrer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lehrer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mueller@bzt.ch",
                            Name = "Herr Müller"
                        },
                        new
                        {
                            Id = 2,
                            Email = "schmidt@bzt.ch",
                            Name = "Frau Schmidt"
                        },
                        new
                        {
                            Id = 3,
                            Email = "weber@bzt.ch",
                            Name = "Herr Weber"
                        });
                });

            modelBuilder.Entity("StundenPlanApp.Models.Schulzimmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kapazitaet")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Schulzimmer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kapazitaet = 20,
                            Nummer = "A101"
                        },
                        new
                        {
                            Id = 2,
                            Kapazitaet = 25,
                            Nummer = "B205"
                        },
                        new
                        {
                            Id = 3,
                            Kapazitaet = 30,
                            Nummer = "C303"
                        });
                });

            modelBuilder.Entity("StundenPlanApp.Models.StundenplanEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aufgabenstellung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlasseId")
                        .HasColumnType("int");

                    b.Property<int>("LehrerId")
                        .HasColumnType("int");

                    b.Property<int>("SchulzimmerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Uhrzeit")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("KlasseId");

                    b.HasIndex("LehrerId");

                    b.HasIndex("SchulzimmerId");

                    b.ToTable("StundenplanEintraege");
                });

            modelBuilder.Entity("StundenPlanApp.Models.StundenplanEintrag", b =>
                {
                    b.HasOne("StundenPlanApp.Models.Klasse", "Klasse")
                        .WithMany("StundenplanEintraege")
                        .HasForeignKey("KlasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StundenPlanApp.Models.Lehrer", "Lehrer")
                        .WithMany("StundenplanEintraege")
                        .HasForeignKey("LehrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StundenPlanApp.Models.Schulzimmer", "Schulzimmer")
                        .WithMany("StundenplanEintraege")
                        .HasForeignKey("SchulzimmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klasse");

                    b.Navigation("Lehrer");

                    b.Navigation("Schulzimmer");
                });

            modelBuilder.Entity("StundenPlanApp.Models.Klasse", b =>
                {
                    b.Navigation("StundenplanEintraege");
                });

            modelBuilder.Entity("StundenPlanApp.Models.Lehrer", b =>
                {
                    b.Navigation("StundenplanEintraege");
                });

            modelBuilder.Entity("StundenPlanApp.Models.Schulzimmer", b =>
                {
                    b.Navigation("StundenplanEintraege");
                });
#pragma warning restore 612, 618
        }
    }
}
